/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ExclusaoDeDadosRouteImport } from './routes/exclusao-de-dados'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedToolDisparosRouteImport } from './routes/_authenticated/tool.disparos'
import { Route as AuthenticatedToolDisparosIndexRouteImport } from './routes/_authenticated/tool.disparos.index'
import { Route as AuthenticatedToolDisparosSobreRouteImport } from './routes/_authenticated/tool.disparos_.sobre'
import { Route as AuthenticatedToolDisparosManualRouteImport } from './routes/_authenticated/tool.disparos_.manual'
import { Route as AuthenticatedToolDisparosHistoricoRouteImport } from './routes/_authenticated/tool.disparos.historico'
import { Route as AuthenticatedToolDisparosDispararRouteImport } from './routes/_authenticated/tool.disparos.disparar'
import { Route as AuthenticatedToolDisparosContatosRouteImport } from './routes/_authenticated/tool.disparos.contatos'
import { Route as AuthenticatedToolDisparosConfiguracoesRouteImport } from './routes/_authenticated/tool.disparos.configuracoes'
import { Route as AuthenticatedToolDisparosClientesRouteImport } from './routes/_authenticated/tool.disparos.clientes'
import { Route as AuthenticatedToolDisparosAnalyticsRouteImport } from './routes/_authenticated/tool.disparos.analytics'
import { Route as AuthenticatedToolDisparosAgendamentosRouteImport } from './routes/_authenticated/tool.disparos.agendamentos'
import { Route as AuthenticatedOauthMetaCallbackRouteImport } from './routes/_authenticated/oauth.meta.callback'
import { Route as AuthenticatedOauthGoogleCallbackRouteImport } from './routes/_authenticated/oauth.google.callback'
import { Route as AuthenticatedToolDisparosTemplatesIndexRouteImport } from './routes/_authenticated/tool.disparos.templates.index'
import { Route as AuthenticatedToolDisparosTemplatesNovoRouteImport } from './routes/_authenticated/tool.disparos.templates.novo'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeDadosRoute = ExclusaoDeDadosRouteImport.update({
  id: '/exclusao-de-dados',
  path: '/exclusao-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolDisparosRoute =
  AuthenticatedToolDisparosRouteImport.update({
    id: '/tool/disparos',
    path: '/tool/disparos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolDisparosIndexRoute =
  AuthenticatedToolDisparosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedToolDisparosRoute,
  } as any)
const AuthenticatedToolDisparosSobreRoute =
  AuthenticatedToolDisparosSobreRouteImport.update({
    id: '/tool/disparos_/sobre',
    path: '/tool/disparos/sobre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolDisparosManualRoute =
  AuthenticatedToolDisparosManualRouteImport.update({
    id: '/tool/disparos_/manual',
    path: '/tool/disparos/manual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolDisparosHistoricoRoute =
  AuthenticatedToolDisparosHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedToolDisparosRoute,
  } as any)
const AuthenticatedToolDisparosDispararRoute =
  AuthenticatedToolDisparosDispararRouteImport.update({
    id: '/disparar',
    path: '/disparar',
    getParentRoute: () => AuthenticatedToolDisparosRoute,
  } as any)
const AuthenticatedToolDisparosContatosRoute =
  AuthenticatedToolDisparosContatosRouteImport.update({
    id: '/contatos',
    path: '/contatos',
    getParentRoute: () => AuthenticatedToolDisparosRoute,
  } as any)
const AuthenticatedToolDisparosConfiguracoesRoute =
  AuthenticatedToolDisparosConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedToolDisparosRoute,
  } as any)
const AuthenticatedToolDisparosClientesRoute =
  AuthenticatedToolDisparosClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedToolDisparosRoute,
  } as any)
const AuthenticatedToolDisparosAnalyticsRoute =
  AuthenticatedToolDisparosAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedToolDisparosRoute,
  } as any)
const AuthenticatedToolDisparosAgendamentosRoute =
  AuthenticatedToolDisparosAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedToolDisparosRoute,
  } as any)
const AuthenticatedOauthMetaCallbackRoute =
  AuthenticatedOauthMetaCallbackRouteImport.update({
    id: '/oauth/meta/callback',
    path: '/oauth/meta/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOauthGoogleCallbackRoute =
  AuthenticatedOauthGoogleCallbackRouteImport.update({
    id: '/oauth/google/callback',
    path: '/oauth/google/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolDisparosTemplatesIndexRoute =
  AuthenticatedToolDisparosTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedToolDisparosRoute,
  } as any)
const AuthenticatedToolDisparosTemplatesNovoRoute =
  AuthenticatedToolDisparosTemplatesNovoRouteImport.update({
    id: '/templates/novo',
    path: '/templates/novo',
    getParentRoute: () => AuthenticatedToolDisparosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/tool/disparos': typeof AuthenticatedToolDisparosRouteWithChildren
  '/oauth/google/callback': typeof AuthenticatedOauthGoogleCallbackRoute
  '/oauth/meta/callback': typeof AuthenticatedOauthMetaCallbackRoute
  '/tool/disparos/agendamentos': typeof AuthenticatedToolDisparosAgendamentosRoute
  '/tool/disparos/analytics': typeof AuthenticatedToolDisparosAnalyticsRoute
  '/tool/disparos/clientes': typeof AuthenticatedToolDisparosClientesRoute
  '/tool/disparos/configuracoes': typeof AuthenticatedToolDisparosConfiguracoesRoute
  '/tool/disparos/contatos': typeof AuthenticatedToolDisparosContatosRoute
  '/tool/disparos/disparar': typeof AuthenticatedToolDisparosDispararRoute
  '/tool/disparos/historico': typeof AuthenticatedToolDisparosHistoricoRoute
  '/tool/disparos/manual': typeof AuthenticatedToolDisparosManualRoute
  '/tool/disparos/sobre': typeof AuthenticatedToolDisparosSobreRoute
  '/tool/disparos/': typeof AuthenticatedToolDisparosIndexRoute
  '/tool/disparos/templates/novo': typeof AuthenticatedToolDisparosTemplatesNovoRoute
  '/tool/disparos/templates/': typeof AuthenticatedToolDisparosTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/oauth/google/callback': typeof AuthenticatedOauthGoogleCallbackRoute
  '/oauth/meta/callback': typeof AuthenticatedOauthMetaCallbackRoute
  '/tool/disparos/agendamentos': typeof AuthenticatedToolDisparosAgendamentosRoute
  '/tool/disparos/analytics': typeof AuthenticatedToolDisparosAnalyticsRoute
  '/tool/disparos/clientes': typeof AuthenticatedToolDisparosClientesRoute
  '/tool/disparos/configuracoes': typeof AuthenticatedToolDisparosConfiguracoesRoute
  '/tool/disparos/contatos': typeof AuthenticatedToolDisparosContatosRoute
  '/tool/disparos/disparar': typeof AuthenticatedToolDisparosDispararRoute
  '/tool/disparos/historico': typeof AuthenticatedToolDisparosHistoricoRoute
  '/tool/disparos/manual': typeof AuthenticatedToolDisparosManualRoute
  '/tool/disparos/sobre': typeof AuthenticatedToolDisparosSobreRoute
  '/tool/disparos': typeof AuthenticatedToolDisparosIndexRoute
  '/tool/disparos/templates/novo': typeof AuthenticatedToolDisparosTemplatesNovoRoute
  '/tool/disparos/templates': typeof AuthenticatedToolDisparosTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/tool/disparos': typeof AuthenticatedToolDisparosRouteWithChildren
  '/_authenticated/oauth/google/callback': typeof AuthenticatedOauthGoogleCallbackRoute
  '/_authenticated/oauth/meta/callback': typeof AuthenticatedOauthMetaCallbackRoute
  '/_authenticated/tool/disparos/agendamentos': typeof AuthenticatedToolDisparosAgendamentosRoute
  '/_authenticated/tool/disparos/analytics': typeof AuthenticatedToolDisparosAnalyticsRoute
  '/_authenticated/tool/disparos/clientes': typeof AuthenticatedToolDisparosClientesRoute
  '/_authenticated/tool/disparos/configuracoes': typeof AuthenticatedToolDisparosConfiguracoesRoute
  '/_authenticated/tool/disparos/contatos': typeof AuthenticatedToolDisparosContatosRoute
  '/_authenticated/tool/disparos/disparar': typeof AuthenticatedToolDisparosDispararRoute
  '/_authenticated/tool/disparos/historico': typeof AuthenticatedToolDisparosHistoricoRoute
  '/_authenticated/tool/disparos_/manual': typeof AuthenticatedToolDisparosManualRoute
  '/_authenticated/tool/disparos_/sobre': typeof AuthenticatedToolDisparosSobreRoute
  '/_authenticated/tool/disparos/': typeof AuthenticatedToolDisparosIndexRoute
  '/_authenticated/tool/disparos/templates/novo': typeof AuthenticatedToolDisparosTemplatesNovoRoute
  '/_authenticated/tool/disparos/templates/': typeof AuthenticatedToolDisparosTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/exclusao-de-dados'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/dashboard'
    | '/home'
    | '/planos'
    | '/tool/disparos'
    | '/oauth/google/callback'
    | '/oauth/meta/callback'
    | '/tool/disparos/agendamentos'
    | '/tool/disparos/analytics'
    | '/tool/disparos/clientes'
    | '/tool/disparos/configuracoes'
    | '/tool/disparos/contatos'
    | '/tool/disparos/disparar'
    | '/tool/disparos/historico'
    | '/tool/disparos/manual'
    | '/tool/disparos/sobre'
    | '/tool/disparos/'
    | '/tool/disparos/templates/novo'
    | '/tool/disparos/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/exclusao-de-dados'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/dashboard'
    | '/home'
    | '/planos'
    | '/oauth/google/callback'
    | '/oauth/meta/callback'
    | '/tool/disparos/agendamentos'
    | '/tool/disparos/analytics'
    | '/tool/disparos/clientes'
    | '/tool/disparos/configuracoes'
    | '/tool/disparos/contatos'
    | '/tool/disparos/disparar'
    | '/tool/disparos/historico'
    | '/tool/disparos/manual'
    | '/tool/disparos/sobre'
    | '/tool/disparos'
    | '/tool/disparos/templates/novo'
    | '/tool/disparos/templates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/exclusao-de-dados'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/home'
    | '/_authenticated/planos'
    | '/_authenticated/tool/disparos'
    | '/_authenticated/oauth/google/callback'
    | '/_authenticated/oauth/meta/callback'
    | '/_authenticated/tool/disparos/agendamentos'
    | '/_authenticated/tool/disparos/analytics'
    | '/_authenticated/tool/disparos/clientes'
    | '/_authenticated/tool/disparos/configuracoes'
    | '/_authenticated/tool/disparos/contatos'
    | '/_authenticated/tool/disparos/disparar'
    | '/_authenticated/tool/disparos/historico'
    | '/_authenticated/tool/disparos_/manual'
    | '/_authenticated/tool/disparos_/sobre'
    | '/_authenticated/tool/disparos/'
    | '/_authenticated/tool/disparos/templates/novo'
    | '/_authenticated/tool/disparos/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExclusaoDeDadosRoute: typeof ExclusaoDeDadosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-dados': {
      id: '/exclusao-de-dados'
      path: '/exclusao-de-dados'
      fullPath: '/exclusao-de-dados'
      preLoaderRoute: typeof ExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool/disparos': {
      id: '/_authenticated/tool/disparos'
      path: '/tool/disparos'
      fullPath: '/tool/disparos'
      preLoaderRoute: typeof AuthenticatedToolDisparosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool/disparos/': {
      id: '/_authenticated/tool/disparos/'
      path: '/'
      fullPath: '/tool/disparos/'
      preLoaderRoute: typeof AuthenticatedToolDisparosIndexRouteImport
      parentRoute: typeof AuthenticatedToolDisparosRoute
    }
    '/_authenticated/tool/disparos_/sobre': {
      id: '/_authenticated/tool/disparos_/sobre'
      path: '/tool/disparos/sobre'
      fullPath: '/tool/disparos/sobre'
      preLoaderRoute: typeof AuthenticatedToolDisparosSobreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool/disparos_/manual': {
      id: '/_authenticated/tool/disparos_/manual'
      path: '/tool/disparos/manual'
      fullPath: '/tool/disparos/manual'
      preLoaderRoute: typeof AuthenticatedToolDisparosManualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool/disparos/historico': {
      id: '/_authenticated/tool/disparos/historico'
      path: '/historico'
      fullPath: '/tool/disparos/historico'
      preLoaderRoute: typeof AuthenticatedToolDisparosHistoricoRouteImport
      parentRoute: typeof AuthenticatedToolDisparosRoute
    }
    '/_authenticated/tool/disparos/disparar': {
      id: '/_authenticated/tool/disparos/disparar'
      path: '/disparar'
      fullPath: '/tool/disparos/disparar'
      preLoaderRoute: typeof AuthenticatedToolDisparosDispararRouteImport
      parentRoute: typeof AuthenticatedToolDisparosRoute
    }
    '/_authenticated/tool/disparos/contatos': {
      id: '/_authenticated/tool/disparos/contatos'
      path: '/contatos'
      fullPath: '/tool/disparos/contatos'
      preLoaderRoute: typeof AuthenticatedToolDisparosContatosRouteImport
      parentRoute: typeof AuthenticatedToolDisparosRoute
    }
    '/_authenticated/tool/disparos/configuracoes': {
      id: '/_authenticated/tool/disparos/configuracoes'
      path: '/configuracoes'
      fullPath: '/tool/disparos/configuracoes'
      preLoaderRoute: typeof AuthenticatedToolDisparosConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedToolDisparosRoute
    }
    '/_authenticated/tool/disparos/clientes': {
      id: '/_authenticated/tool/disparos/clientes'
      path: '/clientes'
      fullPath: '/tool/disparos/clientes'
      preLoaderRoute: typeof AuthenticatedToolDisparosClientesRouteImport
      parentRoute: typeof AuthenticatedToolDisparosRoute
    }
    '/_authenticated/tool/disparos/analytics': {
      id: '/_authenticated/tool/disparos/analytics'
      path: '/analytics'
      fullPath: '/tool/disparos/analytics'
      preLoaderRoute: typeof AuthenticatedToolDisparosAnalyticsRouteImport
      parentRoute: typeof AuthenticatedToolDisparosRoute
    }
    '/_authenticated/tool/disparos/agendamentos': {
      id: '/_authenticated/tool/disparos/agendamentos'
      path: '/agendamentos'
      fullPath: '/tool/disparos/agendamentos'
      preLoaderRoute: typeof AuthenticatedToolDisparosAgendamentosRouteImport
      parentRoute: typeof AuthenticatedToolDisparosRoute
    }
    '/_authenticated/oauth/meta/callback': {
      id: '/_authenticated/oauth/meta/callback'
      path: '/oauth/meta/callback'
      fullPath: '/oauth/meta/callback'
      preLoaderRoute: typeof AuthenticatedOauthMetaCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oauth/google/callback': {
      id: '/_authenticated/oauth/google/callback'
      path: '/oauth/google/callback'
      fullPath: '/oauth/google/callback'
      preLoaderRoute: typeof AuthenticatedOauthGoogleCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool/disparos/templates/': {
      id: '/_authenticated/tool/disparos/templates/'
      path: '/templates'
      fullPath: '/tool/disparos/templates/'
      preLoaderRoute: typeof AuthenticatedToolDisparosTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedToolDisparosRoute
    }
    '/_authenticated/tool/disparos/templates/novo': {
      id: '/_authenticated/tool/disparos/templates/novo'
      path: '/templates/novo'
      fullPath: '/tool/disparos/templates/novo'
      preLoaderRoute: typeof AuthenticatedToolDisparosTemplatesNovoRouteImport
      parentRoute: typeof AuthenticatedToolDisparosRoute
    }
  }
}

interface AuthenticatedToolDisparosRouteChildren {
  AuthenticatedToolDisparosAgendamentosRoute: typeof AuthenticatedToolDisparosAgendamentosRoute
  AuthenticatedToolDisparosAnalyticsRoute: typeof AuthenticatedToolDisparosAnalyticsRoute
  AuthenticatedToolDisparosClientesRoute: typeof AuthenticatedToolDisparosClientesRoute
  AuthenticatedToolDisparosConfiguracoesRoute: typeof AuthenticatedToolDisparosConfiguracoesRoute
  AuthenticatedToolDisparosContatosRoute: typeof AuthenticatedToolDisparosContatosRoute
  AuthenticatedToolDisparosDispararRoute: typeof AuthenticatedToolDisparosDispararRoute
  AuthenticatedToolDisparosHistoricoRoute: typeof AuthenticatedToolDisparosHistoricoRoute
  AuthenticatedToolDisparosIndexRoute: typeof AuthenticatedToolDisparosIndexRoute
  AuthenticatedToolDisparosTemplatesNovoRoute: typeof AuthenticatedToolDisparosTemplatesNovoRoute
  AuthenticatedToolDisparosTemplatesIndexRoute: typeof AuthenticatedToolDisparosTemplatesIndexRoute
}

const AuthenticatedToolDisparosRouteChildren: AuthenticatedToolDisparosRouteChildren =
  {
    AuthenticatedToolDisparosAgendamentosRoute:
      AuthenticatedToolDisparosAgendamentosRoute,
    AuthenticatedToolDisparosAnalyticsRoute:
      AuthenticatedToolDisparosAnalyticsRoute,
    AuthenticatedToolDisparosClientesRoute:
      AuthenticatedToolDisparosClientesRoute,
    AuthenticatedToolDisparosConfiguracoesRoute:
      AuthenticatedToolDisparosConfiguracoesRoute,
    AuthenticatedToolDisparosContatosRoute:
      AuthenticatedToolDisparosContatosRoute,
    AuthenticatedToolDisparosDispararRoute:
      AuthenticatedToolDisparosDispararRoute,
    AuthenticatedToolDisparosHistoricoRoute:
      AuthenticatedToolDisparosHistoricoRoute,
    AuthenticatedToolDisparosIndexRoute: AuthenticatedToolDisparosIndexRoute,
    AuthenticatedToolDisparosTemplatesNovoRoute:
      AuthenticatedToolDisparosTemplatesNovoRoute,
    AuthenticatedToolDisparosTemplatesIndexRoute:
      AuthenticatedToolDisparosTemplatesIndexRoute,
  }

const AuthenticatedToolDisparosRouteWithChildren =
  AuthenticatedToolDisparosRoute._addFileChildren(
    AuthenticatedToolDisparosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedToolDisparosRoute: typeof AuthenticatedToolDisparosRouteWithChildren
  AuthenticatedOauthGoogleCallbackRoute: typeof AuthenticatedOauthGoogleCallbackRoute
  AuthenticatedOauthMetaCallbackRoute: typeof AuthenticatedOauthMetaCallbackRoute
  AuthenticatedToolDisparosManualRoute: typeof AuthenticatedToolDisparosManualRoute
  AuthenticatedToolDisparosSobreRoute: typeof AuthenticatedToolDisparosSobreRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedToolDisparosRoute: AuthenticatedToolDisparosRouteWithChildren,
  AuthenticatedOauthGoogleCallbackRoute: AuthenticatedOauthGoogleCallbackRoute,
  AuthenticatedOauthMetaCallbackRoute: AuthenticatedOauthMetaCallbackRoute,
  AuthenticatedToolDisparosManualRoute: AuthenticatedToolDisparosManualRoute,
  AuthenticatedToolDisparosSobreRoute: AuthenticatedToolDisparosSobreRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExclusaoDeDadosRoute: ExclusaoDeDadosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
